In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv(r'C:\Users\rahil\Desktop\Nexus-Edge\data.csv')
df

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.00,failed,0,GB,0.00,0.00,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.00,failed,15,US,100.00,2421.00,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.00,failed,3,US,220.00,220.00,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.00,failed,1,US,1.00,1.00,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.00,canceled,14,US,1283.00,1283.00,19500.00
5,1000014025,Monarch Espresso Bar,Restaurants,Food,USD,2016-04-01,50000.0,2016-02-26 13:38:27,52375.00,successful,224,US,52375.00,52375.00,50000.00
6,1000023410,Support Solar Roasted Coffee & Green Energy! ...,Food,Food,USD,2014-12-21,1000.0,2014-12-01 18:30:44,1205.00,successful,16,US,1205.00,1205.00,1000.00
7,1000030581,Chaser Strips. Our Strips make Shots their B*tch!,Drinks,Food,USD,2016-03-17,25000.0,2016-02-01 20:05:12,453.00,failed,40,US,453.00,453.00,25000.00
8,1000034518,SPIN - Premium Retractable In-Ear Headphones w...,Product Design,Design,USD,2014-05-29,125000.0,2014-04-24 18:14:43,8233.00,canceled,58,US,8233.00,8233.00,125000.00
9,100004195,STUDIO IN THE SKY - A Documentary Feature Film...,Documentary,Film & Video,USD,2014-08-10,65000.0,2014-07-11 21:55:48,6240.57,canceled,43,US,6240.57,6240.57,65000.00
10,100004721,Of Jesus and Madmen,Nonfiction,Publishing,CAD,2013-10-09,2500.0,2013-09-09 18:19:37,0.00,failed,0,CA,0.00,0.00,2406.39
11,100005484,Lisa Lim New CD!,Indie Rock,Music,USD,2013-04-08,12500.0,2013-03-09 06:42:58,12700.00,successful,100,US,12700.00,12700.00,12500.00
12,1000055792,The Cottage Market,Crafts,Crafts,USD,2014-10-02,5000.0,2014-09-02 17:11:50,0.00,failed,0,US,0.00,0.00,5000.00
13,1000056157,G-Spot Place for Gamers to connect with eachot...,Games,Games,USD,2016-03-25,200000.0,2016-02-09 23:01:12,0.00,failed,0,US,0.00,0.00,200000.00
14,1000057089,Tombstone: Old West tabletop game and miniatur...,Tabletop Games,Games,GBP,2017-05-03,5000.0,2017-04-05 19:44:18,94175.00,successful,761,GB,57763.78,121857.33,6469.73
15,1000064368,Survival Rings,Design,Design,USD,2015-02-28,2500.0,2015-01-29 02:10:53,664.00,failed,11,US,664.00,664.00,2500.00
16,1000064918,The Beard,Comic Books,Comics,USD,2014-11-08,1500.0,2014-10-09 22:27:52,395.00,failed,16,US,395.00,395.00,1500.00
17,1000068480,Notes From London: Above & Below,Art Books,Publishing,USD,2015-05-10,3000.0,2015-04-10 21:20:54,789.00,failed,20,US,789.00,789.00,3000.00
18,1000070642,Mike Corey's Darkness & Light Album,Music,Music,USD,2012-08-17,250.0,2012-08-02 14:11:32,250.00,successful,7,US,250.00,250.00,250.00
19,1000071625,Boco Tea,Food,Food,USD,2012-06-02,5000.0,2012-05-03 17:24:32,1781.00,failed,40,US,1781.00,1781.00,5000.00
20,1000072011,CMUK. Shoes: Take on Life Feet First.,Fashion,Fashion,USD,2013-12-30,20000.0,2013-11-25 07:06:11,34268.00,successful,624,US,34268.00,34268.00,20000.00
21,1000081649,MikeyJ clothing brand fundraiser,Childrenswear,Fashion,AUD,2017-09-07,2500.0,2017-08-08 01:20:20,1.00,failed,1,AU,0.00,0.81,2026.10
22,1000082254,Alice in Wonderland in G Minor,Theater,Theater,USD,2014-06-15,3500.0,2014-05-16 10:10:38,650.00,failed,12,US,650.00,650.00,3500.00
23,1000087442,Mountain brew: A quest for alcohol sustainability,Drinks,Food,NOK,2015-02-25,500.0,2015-01-26 19:17:33,48.00,failed,3,NO,6.18,6.29,65.55
24,1000091520,The Book Zoo - A Mini-Comic,Comics,Comics,USD,2014-11-12,175.0,2014-10-23 17:15:50,701.66,successful,66,US,701.66,701.66,175.00
25,1000102741,Matt Cavenaugh & Jenny Powers make their 1st a...,Music,Music,USD,2011-01-06,10000.0,2010-12-07 23:16:50,15827.00,successful,147,US,15827.00,15827.00,10000.00
26,1000103948,Superhero Teddy Bear,DIY,Crafts,GBP,2016-01-05,12000.0,2015-12-06 20:09:06,0.00,failed,0,GB,0.00,0.00,17489.65
27,1000104688,Permaculture Skills,Webseries,Film & Video,CAD,2014-12-14,17757.0,2014-11-14 18:02:00,48905.00,successful,571,CA,43203.25,42174.03,15313.04
28,1000104953,Rebel Army Origins: The Heroic Story Of Major ...,Comics,Comics,GBP,2016-01-28,100.0,2015-12-29 16:59:29,112.38,successful,27,GB,167.70,160.60,142.91
29,100011318,My Moon - Animated Short Film,Animation,Film & Video,USD,2017-05-03,50000.0,2017-04-03 17:11:33,57577.31,successful,840,US,10120.00,57577.31,50000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378631,999832803,MONSTROCARDS- A Creative Drawing Game of Horri...,Playing Cards,Games,USD,2014-10-03,10000.0,2014-09-03 19:53:50,13861.50,successful,413,US,13861.50,13861.50,10000.00
378632,99984851,"""Loreto""",Comedy,Film & Video,USD,2014-06-05,12000.0,2014-05-06 23:50:34,0.00,failed,0,US,0.00,0.00,12000.00
378633,999865831,STATE OF G - Men's Blazer Jacket & Women's Car...,Apparel,Fashion,USD,2014-12-13,25000.0,2014-11-13 17:16:17,11643.00,failed,97,US,11643.00,11643.00,25000.00
378634,999867839,Transcaucasia,Photography,Photography,USD,2011-01-08,4000.0,2010-11-08 02:43:59,3531.00,failed,37,US,3531.00,3531.00,4000.00
378635,99987261,"You're Not Cis, You Just Think You Are: My Enb...",Nonfiction,Publishing,USD,2015-09-24,800.0,2015-08-25 22:37:14,70.00,failed,5,US,70.00,70.00,800.00
378636,999877902,Little Saturday's Debut Album,Country & Folk,Music,CAD,2014-12-17,5000.0,2014-11-17 17:50:12,5435.00,successful,78,CA,4814.88,4686.96,4311.83
378637,999878813,Ways to Look at the Moon,Shorts,Film & Video,USD,2017-10-13,10000.0,2017-08-29 06:57:28,10245.00,successful,123,US,145.00,10245.00,10000.00
378638,999880710,Terminal Uniqueness,Nonfiction,Publishing,USD,2014-08-15,5000.0,2014-07-15 02:10:39,18.00,failed,5,US,18.00,18.00,5000.00
378639,999884445,Superette Tea - Boldly Caffeinated Loose Leaf Tea,Drinks,Food,USD,2015-12-03,5000.0,2015-11-03 13:04:14,5579.00,successful,103,US,5579.00,5579.00,5000.00
378640,999893629,Ciridian Helix (Canceled),Fiction,Publishing,USD,2014-09-11,1000.0,2014-08-08 21:49:31,100.00,canceled,2,US,100.00,100.00,1000.00
378641,99991751,Here is the oasis for the youngest in the world.,Product Design,Design,CHF,2015-09-04,80000.0,2015-07-06 18:00:47,0.00,failed,0,CH,0.00,0.00,82207.27
378642,999929142,ÉPOUVANTAILS : 28mm Figurines de jeux pour KIN...,Tabletop Games,Games,EUR,2017-10-31,1000.0,2017-10-04 11:26:44,1246.00,successful,35,FR,66.72,1452.47,1165.70
378643,999931480,Google Glass Shield (Canceled),3D Printing,Technology,USD,2014-05-26,6500.0,2014-05-05 20:22:45,0.00,canceled,0,US,0.00,0.00,6500.00
378644,999934908,The Manual Bar Blade,Product Design,Design,USD,2015-12-15,3500.0,2015-11-23 07:33:14,6169.00,successful,120,US,6169.00,6169.00,3500.00
378645,999941823,The Chronicles of Erinoth - A Graphic Novel,Comics,Comics,GBP,2013-10-10,16000.0,2013-09-10 22:45:26,2738.00,failed,38,GB,4281.15,4374.99,25566.05
378646,999943841,The Dog Coffee Book,Children's Books,Publishing,USD,2013-11-30,950.0,2013-10-18 21:35:04,1732.02,successful,31,US,1732.02,1732.02,950.00
378647,999950812,The Cease is Increase,Nonfiction,Publishing,USD,2012-09-14,4999.0,2012-08-15 17:11:00,980.00,failed,16,US,980.00,980.00,4999.00
378648,999955533,Cards and Chit Network Season 2! (Canceled),Tabletop Games,Games,USD,2016-02-23,500.0,2016-01-24 16:03:27,121.00,canceled,5,US,121.00,121.00,500.00
378649,999963618,Colorado International Activism Film Festival,Narrative Film,Film & Video,USD,2017-04-09,500.0,2017-02-08 02:28:44,135.00,failed,6,US,45.00,135.00,500.00
378650,99996661,Date Seat - Boston iOS App,Apps,Technology,USD,2016-09-05,6000.0,2016-07-29 15:36:29,0.00,failed,0,US,0.00,0.00,6000.00
378651,999969812,AT THE BEACH,Classical Music,Music,CAD,2014-03-22,5000.0,2014-02-20 01:00:16,5501.00,successful,78,CA,5019.92,4983.69,4529.81
378652,999971898,Beach Wrestling Documentary,Documentary,Film & Video,NOK,2015-04-28,20000.0,2015-03-29 21:30:33,21500.00,successful,36,NO,2698.97,2875.83,2675.19
378653,999972264,Islanda,Documentary,Film & Video,USD,2012-03-16,1700.0,2012-02-15 04:31:10,25.00,failed,1,US,25.00,25.00,1700.00
378654,999975836,"Homemade fresh dog food, Cleveland OH",Small Batch,Food,USD,2017-04-19,6500.0,2017-03-20 22:08:22,154.00,failed,4,US,0.00,154.00,6500.00
378655,999976312,Angela's Poetry (Canceled),Poetry,Publishing,CAD,2014-09-20,5500.0,2014-08-06 03:46:07,0.00,canceled,0,CA,0.00,0.00,4949.60
378656,999976400,ChknTruk Nationwide Charity Drive 2014 (Canceled),Documentary,Film & Video,USD,2014-10-17,50000.0,2014-09-17 02:35:30,25.00,canceled,1,US,25.00,25.00,50000.00
378657,999977640,The Tribe,Narrative Film,Film & Video,USD,2011-07-19,1500.0,2011-06-22 03:35:14,155.00,failed,5,US,155.00,155.00,1500.00
378658,999986353,Walls of Remedy- New lesbian Romantic Comedy f...,Narrative Film,Film & Video,USD,2010-08-16,15000.0,2010-07-01 19:40:30,20.00,failed,1,US,20.00,20.00,15000.00
378659,999987933,BioDefense Education Kit,Technology,Technology,USD,2016-02-13,15000.0,2016-01-13 18:13:53,200.00,failed,6,US,200.00,200.00,15000.00
378660,999988282,Nou Renmen Ayiti! We Love Haiti!,Performance Art,Art,USD,2011-08-16,2000.0,2011-07-19 09:07:47,524.00,failed,17,US,524.00,524.00,2000.00

In [2]:
df=df.drop('ID',axis=1)
df=df.drop('currency',axis=1)
df=df.drop('usd pledged',axis=1)
df=df.drop('goal',axis=1)
x=df
x.shape

(378661, 11)

In [3]:
x.insert(11,'goal',(x['usd_goal_real']).astype(int))
x=x.drop('usd_goal_real',axis=1)
x
y=x['state']
y

0             failed
1             failed
2             failed
3             failed
4           canceled
5         successful
6         successful
7             failed
8           canceled
9           canceled
10            failed
11        successful
12            failed
13            failed
14        successful
15            failed
16            failed
17            failed
18        successful
19            failed
20        successful
21            failed
22            failed
23            failed
24        successful
25        successful
26            failed
27        successful
28        successful
29        successful
             ...
378631    successful
378632        failed
378633        failed
378634        failed
378635        failed
378636    successful
378637    successful
378638        failed
378639    successful
378640      canceled
378641        failed
378642    successful
378643      canceled
378644    successful
378645        failed
378646    successful
378647        failed
378648      canceled
378649        failed
378650        failed
378651    successful
378652    successful
378653        failed
378654        failed
378655      canceled
378656      canceled
378657        failed
378658        failed
378659        failed
378660        failed
Name: state, Length: 378661, dtype: object

In [20]:
x=x.drop('country',axis=1)
from sklearn import preprocessing
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import shutil
import os
import requests
import base64


# Encode text values to dummy variables(i.e. [1,0,0],[0,1,0],[0,0,1] for red,green,blue)
def encode_text_dummy(df, name):
    dummies = pd.get_dummies(df[name])
    for x in dummies.columns:
        dummy_name = "{}-{}".format(name, x)
        df[dummy_name] = dummies[x]
    df.drop(name, axis=1, inplace=True)


# Encode text values to a single dummy variable.  The new columns (which do not replace the old) will have a 1
# at every location where the original column (name) matches each of the target_values.  One column is added for
# each target value.
def encode_text_single_dummy(df, name, target_values):
    for tv in target_values:
        l = list(df[name].astype(str))
        l = [1 if str(x) == str(tv) else 0 for x in l]
        name2 = "{}-{}".format(name, tv)
        df[name2] = l


# Encode text values to indexes(i.e. [1],[2],[3] for red,green,blue).
def encode_text_index(df, name):
    le = preprocessing.LabelEncoder()
    df[name] = le.fit_transform(df[name])
    return le.classes_


# Encode a numeric column as zscores
def encode_numeric_zscore(df, name, mean=None, sd=None):
    if mean is None:
        mean = df[name].mean()

    if sd is None:
        sd = df[name].std()

    df[name] = (df[name] - mean) / sd


# Convert all missing values in the specified column to the median
def missing_median(df, name):
    med = df[name].median()
    df[name] = df[name].fillna(med)


# Convert all missing values in the specified column to the default
def missing_default(df, name, default_value):
    df[name] = df[name].fillna(default_value)


# Convert a Pandas dataframe to the x,y inputs that TensorFlow needs
def to_xy(df, target):
    result = []
    for x in df.columns:
        if x != target:
            result.append(x)
    # find out the type of the target column.  Is it really this hard? :(
    target_type = df[target].dtypes
    target_type = target_type[0] if hasattr(target_type, '__iter__') else target_type
    # Encode to int for classification, float otherwise. TensorFlow likes 32 bits.
    if target_type in (np.int64, np.int32):
        # Classification
        dummies = pd.get_dummies(df[target])
        return df.as_matrix(result).astype(np.float32), dummies.as_matrix().astype(np.float32)
    else:
        # Regression
        return df.as_matrix(result).astype(np.float32), df.as_matrix([target]).astype(np.float32)

# Nicely formatted time string
def hms_string(sec_elapsed):
    h = int(sec_elapsed / (60 * 60))
    m = int((sec_elapsed % (60 * 60)) / 60)
    s = sec_elapsed % 60
    return "{}:{:>02}:{:>05.2f}".format(h, m, s)


# Regression chart.
def chart_regression(pred,y,sort=True):
    t = pd.DataFrame({'pred' : pred, 'y' : y})
    if sort:
        t.sort_values(by=['y'],inplace=True)
    a = plt.plot(t['y'].tolist(),label='expected')
    b = plt.plot(t['pred'].tolist(),label='prediction')
    plt.ylabel('output')
    plt.legend()
    plt.show()

# Remove all rows where the specified column is +/- sd standard deviations
def remove_outliers(df, name, sd):
    drop_rows = df.index[(np.abs(df[name] - df[name].mean()) >= (sd * df[name].std()))]
    df.drop(drop_rows, axis=0, inplace=True)


# Encode a column to a range between normalized_low and normalized_high.
def encode_numeric_range(df, name, normalized_low=-1, normalized_high=1,
                         data_low=None, data_high=None):
    if data_low is None:
        data_low = min(df[name])
        data_high = max(df[name])

    df[name] = ((df[name] - data_low) / (data_high - data_low)) \
               * (normalized_high - normalized_low) + normalized_low
        
# This function submits an assignment.  You can submit an assignment as much as you like, only the final
# submission counts.  The paramaters are as follows:
# data - Pandas dataframe output.
# key - Your student key that was emailed to you.
# no - The assignment class number, should be 1 through 1.
# source_file - The full path to your Python or IPYNB file.  This must have "_class1" as part of its name.  
# .             The number must match your assignment number.  For example "_class2" for class assignment #2.
def submit(data,key,no,source_file=None):
    if source_file is None and '__file__' not in globals(): raise Exception('Must specify a filename when a Jupyter notebook.')
    if source_file is None: source_file = __file__
    suffix = '_class{}'.format(no)
    if suffix not in source_file: raise Exception('{} must be part of the filename.'.format(suffix))
    with open(source_file, "rb") as image_file:
        encoded_python = base64.b64encode(image_file.read()).decode('ascii')
    ext = os.path.splitext(source_file)[-1].lower()
    if ext not in ['.ipynb','.py']: raise Exception("Source file is {} must be .py or .ipynb".format(ext))
    r = requests.post("https://api.heatonresearch.com/assignment-submit",
        headers={'x-api-key':key}, json={'csv':base64.b64encode(data.to_csv(index=False).encode('ascii')).decode("ascii"),
        'assignment': no, 'ext':ext, 'py':encoded_python})
    if r.status_code == 200:
        print("Success: {}".format(r.text))
    else: print("Failure: {}".format(r.text))




from matplotlib.pyplot import figure, show
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import os
from sklearn import metrics
from scipy.stats import zscore
import tensorflow as tf
from keras.models import Sequential
from keras.layers.core import Dense, Activation
from keras.callbacks import EarlyStopping
from sklearn import preprocessing
   
state=encode_text_index(x,'state')
num_classes = len(state)
    
#x,y=to_xy(x,'state')

ValueError: labels ['country'] not contained in axis

In [6]:
from datetime import datetime
#s1 = '10:33:26'
#s2 = '11:15:49' # for example
x['deadline']=pd.to_datetime(x['deadline'])
x['launched']=pd.to_datetime(x['launched'])

FMT_1 = '%Y-%m-%d'
FMT_2 = '%Y-%m-%d %H:%M:%S'
#tdelta = datetime.strptime(x['deadline'], FMT_1) - datetime.strptime(x['launched'], FMT_2)
x['deadline']-x['launched']
x.insert(4,'time_span',(x['deadline']-x['launched']).astype(datetime))

In [7]:
x=x.drop('deadline',axis=1)
x=x.drop('launched',axis=1)
x

,name,category,main_category,time_span,pledged,state,backers,usd_pledged_real,goal
0,The Songs of Adelaide & Abullah,Poetry,Publishing,58 days 11:47:32,0.00,1,0,0.00,1533
1,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,59 days 19:16:03,2421.00,1,15,2421.00,30000
2,Where is Hank?,Narrative Film,Film & Video,44 days 23:39:10,220.00,1,3,220.00,45000
3,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,29 days 20:35:49,1.00,1,1,1.00,5000
4,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,55 days 15:24:57,1283.00,0,14,1283.00,19500
5,Monarch Espresso Bar,Restaurants,Food,34 days 10:21:33,52375.00,3,224,52375.00,50000
6,Support Solar Roasted Coffee & Green Energy! ...,Food,Food,19 days 05:29:16,1205.00,3,16,1205.00,1000
7,Chaser Strips. Our Strips make Shots their B*tch!,Drinks,Food,44 days 03:54:48,453.00,1,40,453.00,25000
8,SPIN - Premium Retractable In-Ear Headphones w...,Product Design,Design,34 days 05:45:17,8233.00,0,58,8233.00,125000
9,STUDIO IN THE SKY - A Documentary Feature Film...,Documentary,Film & Video,29 days 02:04:12,6240.57,0,43,6240.57,65000
10,Of Jesus and Madmen,Nonfiction,Publishing,29 days 05:40:23,0.00,1,0,0.00,2406
11,Lisa Lim New CD!,Indie Rock,Music,29 days 17:17:02,12700.00,3,100,12700.00,12500
12,The Cottage Market,Crafts,Crafts,29 days 06:48:10,0.00,1,0,0.00,5000
13,G-Spot Place for Gamers to connect with eachot...,Games,Games,44 days 00:58:48,0.00,1,0,0.00,200000
14,Tombstone: Old West tabletop game and miniatur...,Tabletop Games,Games,27 days 04:15:42,94175.00,3,761,121857.33,6469
15,Survival Rings,Design,Design,29 days 21:49:07,664.00,1,11,664.00,2500
16,The Beard,Comic Books,Comics,29 days 01:32:08,395.00,1,16,395.00,1500
17,Notes From London: Above & Below,Art Books,Publishing,29 days 02:39:06,789.00,1,20,789.00,3000
18,Mike Corey's Darkness & Light Album,Music,Music,14 days 09:48:28,250.00,3,7,250.00,250
19,Boco Tea,Food,Food,29 days 06:35:28,1781.00,1,40,1781.00,5000
20,CMUK. Shoes: Take on Life Feet First.,Fashion,Fashion,34 days 16:53:49,34268.00,3,624,34268.00,20000
21,MikeyJ clothing brand fundraiser,Childrenswear,Fashion,29 days 22:39:40,1.00,1,1,0.81,2026
22,Alice in Wonderland in G Minor,Theater,Theater,29 days 13:49:22,650.00,1,12,650.00,3500
23,Mountain brew: A quest for alcohol sustainability,Drinks,Food,29 days 04:42:27,48.00,1,3,6.29,65
24,The Book Zoo - A Mini-Comic,Comics,Comics,19 days 06:44:10,701.66,3,66,701.66,175
25,Matt Cavenaugh & Jenny Powers make their 1st a...,Music,Music,29 days 00:43:10,15827.00,3,147,15827.00,10000
26,Superhero Teddy Bear,DIY,Crafts,29 days 03:50:54,0.00,1,0,0.00,17489
27,Permaculture Skills,Webseries,Film & Video,29 days 05:58:00,48905.00,3,571,42174.03,15313
28,Rebel Army Origins: The Heroic Story Of Major ...,Comics,Comics,29 days 07:00:31,112.38,3,27,160.60,142
29,My Moon - Animated Short Film,Animation,Film & Video,29 days 06:48:27,57577.31,3,840,57577.31,50000
...,...,...,...,...,...,...,...,...,...
378631,MONSTROCARDS- A Creative Drawing Game of Horri...,Playing Cards,Games,29 days 04:06:10,13861.50,3,413,13861.50,10000
378632,"""Loreto""",Comedy,Film & Video,29 days 00:09:26,0.00,1,0,0.00,12000
378633,STATE OF G - Men's Blazer Jacket & Women's Car...,Apparel,Fashion,29 days 06:43:43,11643.00,1,97,11643.00,25000
378634,Transcaucasia,Photography,Photography,60 days 21:16:01,3531.00,1,37,3531.00,4000
378635,"You're Not Cis, You Just Think You Are: My Enb...",Nonfiction,Publishing,29 days 01:22:46,70.00,1,5,70.00,800
378636,Little Saturday's Debut Album,Country & Folk,Music,29 days 06:09:48,5435.00,3,78,4686.96,4311
378637,Ways to Look at the Moon,Shorts,Film & Video,44 days 17:02:32,10245.00,3,123,10245.00,10000
378638,Terminal Uniqueness,Nonfiction,Publishing,30 days 21:49:21,18.00,1,5,18.00,5000
378639,Superette Tea - Boldly Caffeinated Loose Leaf Tea,Drinks,Food,29 days 10:55:46,5579.00,3,103,5579.00,5000
378640,Ciridian Helix (Canceled),Fiction,Publishing,33 days 02:10:29,100.00,0,2,100.00,1000
378641,Here is the oasis for the youngest in the world.,Product Design,Design,59 days 05:59:13,0.00,1,0,0.00,82207
378642,ÉPOUVANTAILS : 28mm Figurines de jeux pour KIN...,Tabletop Games,Games,26 days 12:33:16,1246.00,3,35,1452.47,1165
378643,Google Glass Shield (Canceled),3D Printing,Technology,20 days 03:37:15,0.00,0,0,0.00,6500
378644,The Manual Bar Blade,Product Design,Design,21 days 16:26:46,6169.00,3,120,6169.00,3500
378645,The Chronicles of Erinoth - A Graphic Novel,Comics,Comics,29 days 01:14:34,2738.00,1,38,4374.99,25566
378646,The Dog Coffee Book,Children's Books,Publishing,42 days 02:24:56,1732.02,3,31,1732.02,950
378647,The Cease is Increase,Nonfiction,Publishing,29 days 06:49:00,980.00,1,16,980.00,4999
378648,Cards and Chit Network Season 2! (Canceled),Tabletop Games,Games,29 days 07:56:33,121.00,0,5,121.00,500
378649,Colorado International Activism Film Festival,Narrative Film,Film & Video,59 days 21:31:16,135.00,1,6,135.00,500
378650,Date Seat - Boston iOS App,Apps,Technology,37 days 08:23:31,0.00,1,0,0.00,6000
378651,AT THE BEACH,Classical Music,Music,29 days 22:59:44,5501.00,3,78,4983.69,4529
378652,Beach Wrestling Documentary,Documentary,Film & Video,29 days 02:29:27,21500.00,3,36,2875.83,2675
378653,Islanda,Documentary,Film & Video,29 days 19:28:50,25.00,1,1,25.00,1700
378654,"Homemade fresh dog food, Cleveland OH",Small Batch,Food,29 days 01:51:38,154.00,1,4,154.00,6500
378655,Angela's Poetry (Canceled),Poetry,Publishing,44 days 20:13:53,0.00,0,0,0.00,4949
378656,ChknTruk Nationwide Charity Drive 2014 (Canceled),Documentary,Film & Video,29 days 21:24:30,25.00,0,1,25.00,50000
378657,The Tribe,Narrative Film,Film & Video,26 days 20:24:46,155.00,1,5,155.00,1500
378658,Walls of Remedy- New lesbian Romantic Comedy f...,Narrative Film,Film & Video,45 days 04:19:30,20.00,1,1,20.00,15000
378659,BioDefense Education Kit,Technology,Technology,30 days 05:46:07,200.00,1,6,200.00,15000
378660,Nou Renmen Ayiti! We Love Haiti!,Performance Art,Art,27 days 14:52:13,524.00,1,17,524.00,2000

In [8]:
x=x.drop('name',axis=1)
x=x.drop('category',axis=1)
x=x.drop('main_category',axis=1)
x

               time_span   pledged  state  backers  usd_pledged_real    goal
0       58 days 11:47:32      0.00      1        0              0.00    1533
1       59 days 19:16:03   2421.00      1       15           2421.00   30000
2       44 days 23:39:10    220.00      1        3            220.00   45000
3       29 days 20:35:49      1.00      1        1              1.00    5000
4       55 days 15:24:57   1283.00      0       14           1283.00   19500
5       34 days 10:21:33  52375.00      3      224          52375.00   50000
6       19 days 05:29:16   1205.00      3       16           1205.00    1000
7       44 days 03:54:48    453.00      1       40            453.00   25000
8       34 days 05:45:17   8233.00      0       58           8233.00  125000
9       29 days 02:04:12   6240.57      0       43           6240.57   65000
10      29 days 05:40:23      0.00      1        0              0.00    2406
11      29 days 17:17:02  12700.00      3      100          12700.00   12500
12      29 days 06:48:10      0.00      1        0              0.00    5000
13      44 days 00:58:48      0.00      1        0              0.00  200000
14      27 days 04:15:42  94175.00      3      761         121857.33    6469
15      29 days 21:49:07    664.00      1       11            664.00    2500
16      29 days 01:32:08    395.00      1       16            395.00    1500
17      29 days 02:39:06    789.00      1       20            789.00    3000
18      14 days 09:48:28    250.00      3        7            250.00     250
19      29 days 06:35:28   1781.00      1       40           1781.00    5000
20      34 days 16:53:49  34268.00      3      624          34268.00   20000
21      29 days 22:39:40      1.00      1        1              0.81    2026
22      29 days 13:49:22    650.00      1       12            650.00    3500
23      29 days 04:42:27     48.00      1        3              6.29      65
24      19 days 06:44:10    701.66      3       66            701.66     175
25      29 days 00:43:10  15827.00      3      147          15827.00   10000
26      29 days 03:50:54      0.00      1        0              0.00   17489
27      29 days 05:58:00  48905.00      3      571          42174.03   15313
28      29 days 07:00:31    112.38      3       27            160.60     142
29      29 days 06:48:27  57577.31      3      840          57577.31   50000
...                  ...       ...    ...      ...               ...     ...
378631  29 days 04:06:10  13861.50      3      413          13861.50   10000
378632  29 days 00:09:26      0.00      1        0              0.00   12000
378633  29 days 06:43:43  11643.00      1       97          11643.00   25000
378634  60 days 21:16:01   3531.00      1       37           3531.00    4000
378635  29 days 01:22:46     70.00      1        5             70.00     800
378636  29 days 06:09:48   5435.00      3       78           4686.96    4311
378637  44 days 17:02:32  10245.00      3      123          10245.00   10000
378638  30 days 21:49:21     18.00      1        5             18.00    5000
378639  29 days 10:55:46   5579.00      3      103           5579.00    5000
378640  33 days 02:10:29    100.00      0        2            100.00    1000
378641  59 days 05:59:13      0.00      1        0              0.00   82207
378642  26 days 12:33:16   1246.00      3       35           1452.47    1165
378643  20 days 03:37:15      0.00      0        0              0.00    6500
378644  21 days 16:26:46   6169.00      3      120           6169.00    3500
378645  29 days 01:14:34   2738.00      1       38           4374.99   25566
378646  42 days 02:24:56   1732.02      3       31           1732.02     950
378647  29 days 06:49:00    980.00      1       16            980.00    4999
378648  29 days 07:56:33    121.00      0        5            121.00     500
378649  59 days 21:31:16    135.00      1        6            135.00     500
378650  37 days 08:23:31      0.00      1        0              0.00    6000
378651  29 days 22:59:44   5501.00      3       78           4983.69    4529
378652  29 days 02:29:27  21500.00      3       36           2875.83    2675
378653  29 days 19:28:50     25.00      1        1             25.00    1700
378654  29 days 01:51:38    154.00      1        4            154.00    6500
378655  44 days 20:13:53      0.00      0        0              0.00    4949
378656  29 days 21:24:30     25.00      0        1             25.00   50000
378657  26 days 20:24:46    155.00      1        5            155.00    1500
378658  45 days 04:19:30     20.00      1        1             20.00   15000
378659  30 days 05:46:07    200.00      1        6            200.00   15000
378660  27 days 14:52:13    524.00      1       17            524.00    2000

[378661 rows x 6 columns]

In [9]:
y=x['state']
y

0         1
1         1
2         1
3         1
4         0
5         3
6         3
7         1
8         0
9         0
10        1
11        3
12        1
13        1
14        3
15        1
16        1
17        1
18        3
19        1
20        3
21        1
22        1
23        1
24        3
25        3
26        1
27        3
28        3
29        3
         ..
378631    3
378632    1
378633    1
378634    1
378635    1
378636    3
378637    3
378638    1
378639    3
378640    0
378641    1
378642    3
378643    0
378644    3
378645    1
378646    3
378647    1
378648    0
378649    1
378650    1
378651    3
378652    3
378653    1
378654    1
378655    0
378656    0
378657    1
378658    1
378659    1
378660    1
Name: state, Length: 378661, dtype: int64

In [10]:
x['time_span']=pd.to_timedelta(x['time_span'])

In [11]:
#x['time_span'].days.astype(int)
days = x['time_span'].astype('timedelta64[D]')
days

0         58.0
1         59.0
2         44.0
3         29.0
4         55.0
5         34.0
6         19.0
7         44.0
8         34.0
9         29.0
10        29.0
11        29.0
12        29.0
13        44.0
14        27.0
15        29.0
16        29.0
17        29.0
18        14.0
19        29.0
20        34.0
21        29.0
22        29.0
23        29.0
24        19.0
25        29.0
26        29.0
27        29.0
28        29.0
29        29.0
          ...
378631    29.0
378632    29.0
378633    29.0
378634    60.0
378635    29.0
378636    29.0
378637    44.0
378638    30.0
378639    29.0
378640    33.0
378641    59.0
378642    26.0
378643    20.0
378644    21.0
378645    29.0
378646    42.0
378647    29.0
378648    29.0
378649    59.0
378650    37.0
378651    29.0
378652    29.0
378653    29.0
378654    29.0
378655    44.0
378656    29.0
378657    26.0
378658    45.0
378659    30.0
378660    27.0
Name: time_span, Length: 378661, dtype: float64

In [12]:
#x.insert(4,'days',days)
x=x.drop('time_span',axis=1)

In [13]:
x.insert(4,'days',days)
x

         pledged  state  backers  usd_pledged_real  days    goal
0           0.00      1        0              0.00  58.0    1533
1        2421.00      1       15           2421.00  59.0   30000
2         220.00      1        3            220.00  44.0   45000
3           1.00      1        1              1.00  29.0    5000
4        1283.00      0       14           1283.00  55.0   19500
5       52375.00      3      224          52375.00  34.0   50000
6        1205.00      3       16           1205.00  19.0    1000
7         453.00      1       40            453.00  44.0   25000
8        8233.00      0       58           8233.00  34.0  125000
9        6240.57      0       43           6240.57  29.0   65000
10          0.00      1        0              0.00  29.0    2406
11      12700.00      3      100          12700.00  29.0   12500
12          0.00      1        0              0.00  29.0    5000
13          0.00      1        0              0.00  44.0  200000
14      94175.00      3      761         121857.33  27.0    6469
15        664.00      1       11            664.00  29.0    2500
16        395.00      1       16            395.00  29.0    1500
17        789.00      1       20            789.00  29.0    3000
18        250.00      3        7            250.00  14.0     250
19       1781.00      1       40           1781.00  29.0    5000
20      34268.00      3      624          34268.00  34.0   20000
21          1.00      1        1              0.81  29.0    2026
22        650.00      1       12            650.00  29.0    3500
23         48.00      1        3              6.29  29.0      65
24        701.66      3       66            701.66  19.0     175
25      15827.00      3      147          15827.00  29.0   10000
26          0.00      1        0              0.00  29.0   17489
27      48905.00      3      571          42174.03  29.0   15313
28        112.38      3       27            160.60  29.0     142
29      57577.31      3      840          57577.31  29.0   50000
...          ...    ...      ...               ...   ...     ...
378631  13861.50      3      413          13861.50  29.0   10000
378632      0.00      1        0              0.00  29.0   12000
378633  11643.00      1       97          11643.00  29.0   25000
378634   3531.00      1       37           3531.00  60.0    4000
378635     70.00      1        5             70.00  29.0     800
378636   5435.00      3       78           4686.96  29.0    4311
378637  10245.00      3      123          10245.00  44.0   10000
378638     18.00      1        5             18.00  30.0    5000
378639   5579.00      3      103           5579.00  29.0    5000
378640    100.00      0        2            100.00  33.0    1000
378641      0.00      1        0              0.00  59.0   82207
378642   1246.00      3       35           1452.47  26.0    1165
378643      0.00      0        0              0.00  20.0    6500
378644   6169.00      3      120           6169.00  21.0    3500
378645   2738.00      1       38           4374.99  29.0   25566
378646   1732.02      3       31           1732.02  42.0     950
378647    980.00      1       16            980.00  29.0    4999
378648    121.00      0        5            121.00  29.0     500
378649    135.00      1        6            135.00  59.0     500
378650      0.00      1        0              0.00  37.0    6000
378651   5501.00      3       78           4983.69  29.0    4529
378652  21500.00      3       36           2875.83  29.0    2675
378653     25.00      1        1             25.00  29.0    1700
378654    154.00      1        4            154.00  29.0    6500
378655      0.00      0        0              0.00  44.0    4949
378656     25.00      0        1             25.00  29.0   50000
378657    155.00      1        5            155.00  26.0    1500
378658     20.00      1        1             20.00  45.0   15000
378659    200.00      1        6            200.00  30.0   15000
378660    524.00      1       17            524.00  27.0    2000

[378661 rows x 6 columns]

In [27]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25,random_state=42)
svm = SVC(kernel='rbf', C=1).fit(x_train[:40500], y_train[:40500])

score=np.sqrt(metrics.mean_squared_error(pred,y_test))
print("Score (RMSE): {}".format(score))
svm.score(x_test[:10000], y_test[:10000])

Score (RMSE): 1.3103252390372293

0.53539999999999999

In [ ]:
def chart_regression(pred,y,sort=True):
    t = pd.DataFrame({'pred' : pred, 'y' : y})
    if sort:
        t.sort_values(by=['y'],inplace=True)
    a = plt.plot(t['y'].tolist(),label='expected')
    b = plt.plot(t['pred'].tolist(),label='prediction')
    plt.ylabel('output')
    plt.legend()
    plt.show()

pred=svm.predict(x_test)
chart_regression(pred,y_test)